UPDATE `{prefix}config` SET `value` = '# SECTION 1\r\n# correct urls for yahoo bot\r\nRewriteCond %{REQUEST_URI} !\..+$\r\nRewriteCond %{REQUEST_URI} !/$\r\nRewriteRule (.*) %{REQUEST_URI}/ [R=301,L]\r\n\r\n# mod_rewrite rules for plugins\r\nRewriteRule ^mod/([a-zA-Z0-9]+)/$ controller.php?plugin=$1 [QSA,L]\r\nRewriteRule ^mod/([a-zA-Z0-9]+)/([a-zA-Z0-9]+)/$ controller.php?plugin=$1&file=$2 [QSA,L]\r\nRewriteRule ^mod/([a-zA-Z0-9]+)/([a-zA-Z0-9]+).html$ controller.php?plugin=$1&file=$2 [QSA,L]\r\n\r\n# mod_rewrite rules for view account page\r\nRewriteRule ^accounts/$ accounts.php [QSA,L]\r\nRewriteRule ^accounts/(.*)/$ accounts.php?alpha=$1 [QSA,L]\r\nRewriteRule ^accounts/(.*).html$ view-account.php?account=$1 [QSA,L]\r\n\r\n' WHERE `name` = 'htaccessfile_1';
ALTER TABLE `{prefix}language` CHANGE `category` `category` ENUM( 'admin', 'frontend', 'common', 'page', 'tooltip' ) NOT NULL DEFAULT 'frontend';
INSERT INTO `{prefix}language` (`id`, `key`, `value`, `lang`, `category`, `code`) VALUES
(NULL, 'are_you_sure_to_resend_confirmation', 'Are you sure you want to resend confirmation email?', 'English', 'admin', 'en'),
(NULL, 'plugin_changelog', 'Changelog', 'English', 'admin', 'en'),
(NULL, 'add_another_one_to_same', 'Add another in the same category', 'English', 'admin', 'en'),
(NULL, 'listing_expired', 'Expired', 'English', 'admin', 'en'),
(NULL, 'block_type_tip_plain', 'Plain type is used when you wish to display simple information. It will be displayed as is plus escaping HTML tags.', 'English', 'admin', 'en'),
(NULL, 'block_type_tip_html', 'HTML type is used for formatted HTML display. You can use WYSIWYG editor for your block content. This block can be also used for JavaScript code, but you <span style="color: red">need to paste it in SOURCE mode</span>.', 'English', 'admin', 'en'),
(NULL, 'block_type_tip_smarty', 'Smarty type block is used for smarty code. You can get more information about Smarty template engine here: <a href="http://www.smarty.net" target="_blank">http://www.smarty.net</a>', 'English', 'admin', 'en'),
(NULL, 'block_type_tip_php', 'PHP is used to have php code in your block content.', 'English', 'admin', 'en'),
(NULL, 'reset_plan', 'Reset Plan', 'English', 'admin', 'en'),
(NULL, 'accounts', 'Enables accounts for your eSyndiCat Directory', 'English', 'tooltip', 'en'),
(NULL, 'accounts_autoapproval', 'Sends out confirmation emails and automatically approves accounts.', 'English', 'tooltip', 'en'),
(NULL, 'accounts_registered', 'Disabling this, reduces spam posts.', 'English', 'tooltip', 'en'),
(NULL, 'admin_online_expiry_time', 'Admin remains logged in during idle.', 'English', 'tooltip', 'en'),
(NULL, 'display_news', 'Displays eSyndiCat news within the adminCP', 'English', 'tooltip', 'en'),
(NULL, 'display_new_plugins', 'Notifies when a new plugin is available.', 'English', 'tooltip', 'en'),
(NULL, 'captcha', 'Activates Captcha', 'English', 'tooltip', 'en'),
(NULL, 'captcha_name', 'kcaptcha is default', 'English', 'tooltip', 'en'),
(NULL, 'captcha_preview', 'Displays what the image will look like.', 'English', 'tooltip', 'en'),
(NULL, 'captcha_case_sensitive', 'Default is enable; Exact entry is needed.', 'English', 'tooltip', 'en'),
(NULL, 'captcha_num_chars', 'Recommended to use 4 or 5 letters.', 'English', 'tooltip', 'en'),
(NULL, 'suggest_category', 'This displays the Submit Category link', 'English', 'tooltip', 'en'),
(NULL, 'use_html_path', 'This places all of the categories as /"yourcategory".html', 'English', 'tooltip', 'en'),
(NULL, 'related', 'Displays the Related Categories links at the bottom of the category used', 'English', 'tooltip', 'en'),
(NULL, 'neighbour', 'Displays Neighbor categories within the category chosen', 'English', 'tooltip', 'en'),
(NULL, 'show_children_listings', 'Shows listings in the categories within the main category', 'English', 'tooltip', 'en'),
(NULL, 'categories_order', 'Preferred sorting can be defined by Title or Order', 'English', 'tooltip', 'en'),
(NULL, 'categories_tree_type', 'Define as a Directory Tree like in 2.2 or Dropdown selection', 'English', 'tooltip', 'en'),
(NULL, 'num_categories_cols', 'Displays the number of columns for your categories', 'English', 'tooltip', 'en'),
(NULL, 'num_listings_display', 'Shows a listing display showing category and listing numbers', 'English', 'tooltip', 'en'),
(NULL, 'subcats_display', 'Displays the subcategories listings under the main category', 'English', 'tooltip', 'en'),
(NULL, 'cron_recip', 'Checks reciprocal status and disables the listing.', 'English', 'tooltip', 'en'),
(NULL, 'cron_broken', 'This updates listing status.', 'English', 'tooltip', 'en'),
(NULL, 'cron_pagerank', 'This will update the pagerank of sites.', 'English', 'tooltip', 'en'),
(NULL, 'cron_num_listings', 'Default is 10; Perfect for shared hosting accounts. VPS 25-35, Dedicated 100.', 'English', 'tooltip', 'en'),
(NULL, 'cron_check_interval', '1 is default; Recommended for large directories.', 'English', 'tooltip', 'en'),
(NULL, 'cron_report_job', 'Sends an email after cronjob is complete.', 'English', 'tooltip', 'en'),
(NULL, 'cron_report_job_extra', 'Includes the what listings were updated in the email.', 'English', 'tooltip', 'en'),
(NULL, 'cron_report_cycle', 'After all listings are checked, An email will notify you.', 'English', 'tooltip', 'en'),
(NULL, 'cron_report_cycle_extra', 'Listing will include all listings that were completed.', 'English', 'tooltip', 'en'),
(NULL, 'cron_backup', 'Enables a backup of your database.', 'English', 'tooltip', 'en'),
(NULL, 'cron_backup_archive', 'Enabled will backup the database into a zip file to conserve space.', 'English', 'tooltip', 'en'),
(NULL, 'cron_backup_interval', 'Default is 30 days, If your site is active, it is recommended to reduce the time.', 'English', 'tooltip', 'en'),
(NULL, 'sponsored_listings', 'Enable to offer paid listings.', 'English', 'tooltip', 'en'),
(NULL, 'currency_symbol', 'Default is $.', 'English', 'tooltip', 'en'),
(NULL, 'sponsored_only', 'Offer only paid listings when enabled.', 'English', 'tooltip', 'en'),
(NULL, 'num_sponsored_display', 'Determines how many will be displayed in your sponsored listings block.', 'English', 'tooltip', 'en'),
(NULL, 'payment_transactions', 'Records the payment transactions of your account holders.', 'English', 'tooltip', 'en'),
(NULL, 'mcross_functionality', 'Enable this to allow submissions to cross categories.', 'English', 'tooltip', 'en'),
(NULL, 'mcross_number_links', 'Determines how many categories a listing is allow to cross.', 'English', 'tooltip', 'en'),
(NULL, 'mcross_only_sponsored', 'Enabled only for Paid listings.', 'English', 'tooltip', 'en'),
(NULL, 'site', 'This will be your site''s name.', 'English', 'tooltip', 'en'),
(NULL, 'site_logo', 'Upload your logo here, keep the image size.', 'English', 'tooltip', 'en'),
(NULL, 'backup', 'Default is backup/  recommended that you do not alter.', 'English', 'tooltip', 'en'),
(NULL, 'admin', 'Default is admin/ recommended that you do not alter.', 'English', 'tooltip', 'en'),
(NULL, 'site_email', 'Email address you wish to get account changes and alerts sent to.', 'English', 'tooltip', 'en'),
(NULL, 'bugs_email', 'Email address you wish to be alerted if there is a problem.', 'English', 'tooltip', 'en'),
(NULL, 'lang', 'Select your preferred language of your site.', 'English', 'tooltip', 'en'),
(NULL, 'charset', 'Default is UTF-8.', 'English', 'tooltip', 'en'),
(NULL, 'date_format', 'Select your preferred date format %e is timezone,  %Y is 4-digit year.', 'English', 'tooltip', 'en'),
(NULL, 'suffix', 'This is the 2nd description for your Title bar.', 'English', 'tooltip', 'en'),
(NULL, 'title_breadcrumb', 'Produces breadcrumbs in Title.', 'English', 'tooltip', 'en'),
(NULL, 'language_switch', 'Allows users on the front of your site changed language.', 'English', 'tooltip', 'en'),
(NULL, 'mod_rewrite', 'Produces SEO friendly URLs.', 'English', 'tooltip', 'en'),
(NULL, 'old_pages_urls', 'Uses the original 2.2 style SEO URLs.', 'English', 'tooltip', 'en'),
(NULL, 'caching', 'If you are using slow shared hosting, this will cache your pages for faster loading.', 'English', 'tooltip', 'en'),
(NULL, 'display_frontend', 'Enabling the Frontend displays your site as intended.', 'English', 'tooltip', 'en'),
(NULL, 'underconstruction', 'If Display Frontend is disabled.  The below message will be shown.', 'English', 'tooltip', 'en'),
(NULL, 'listing_check', 'Enabling this will check from broken listings.', 'English', 'tooltip', 'en'),
(NULL, 'reciprocal_check', 'Enable this for link checking; Cron configuration is required.', 'English', 'tooltip', 'en'),
(NULL, 'reciprocal_required_only_for_free', 'Enable this for gaining a link exchange function.', 'English', 'tooltip', 'en'),
(NULL, 'reciprocal_domain', 'Makes reciprocal domain name sensitive.', 'English', 'tooltip', 'en'),
(NULL, 'reciprocal_text', 'This is your preferred domain you want to promote.', 'English', 'tooltip', 'en'),
(NULL, 'recip_featured', 'Allows reciprocal listings to be featured.', 'English', 'tooltip', 'en'),
(NULL, 'reciprocal_label', 'This text can be edited to fit your needs.', 'English', 'tooltip', 'en'),
(NULL, 'reciprocal_code', 'This code is for the client to paste within his site for Reciprocal listing checks.', 'English', 'tooltip', 'en'),
(NULL, 'duplicate_checking', 'Enables Duplicate listing Check; Frequency is determined in Cron Configuration.', 'English', 'tooltip', 'en'),
(NULL, 'duplicate_type', 'Checks links based on the dropdown choice.', 'English', 'tooltip', 'en'),
(NULL, 'duplicate_visitors', 'Disables Link Checking', 'English', 'tooltip', 'en'),
(NULL, 'allow_listings_submission', 'Enables the Submit Listings button.', 'English', 'tooltip', 'en'),
(NULL, 'auto_approval', 'Automatic Submission approval; Note: Do not enable if you want to manually approve listings.', 'English', 'tooltip', 'en'),
(NULL, 'new_window', 'Opens a new window when directed to the listing.', 'English', 'tooltip', 'en'),
(NULL, 'forward_to_listing_details', 'Opens the on-site listing instead of being forwards to the actual site.', 'English', 'tooltip', 'en'),
(NULL, 'pagerank', 'Shows the pagerank on both the site details and truncated listings.', 'English', 'tooltip', 'en'),
(NULL, 'thumbshot', 'Displays a small screen capture of the listings website.', 'English', 'tooltip', 'en'),
(NULL, 'broken_listings_report', 'Enabling this will check the broken listings and send an email report.\r\n', 'English', 'tooltip', 'en'),
(NULL, 'num_index_listings', 'Selecting how many listings you want displayed per page. Default is 10.', 'English', 'tooltip', 'en'),
(NULL, 'num_get_listings', 'Select the number of listings you want displayed on the Top, New and Popular listings pages.', 'English', 'tooltip', 'en'),
(NULL, 'num_featured_display', 'Displays the selected number of listings you want in the Featured box.', 'English', 'tooltip', 'en'),
(NULL, 'num_partner_display', 'Displays the selected number of listings you want in the Partners box.', 'English', 'tooltip', 'en'),
(NULL, 'html_tags', 'This allows html in the Editors box, this will allow users to display unwanted links within the listing. (Not recommended).', 'English', 'tooltip', 'en'),
(NULL, 'visitor_sorting', 'Enabling this will allow users to view listings by alpha, rank, clicks or date.', 'English', 'tooltip', 'en'),
(NULL, 'listings_sorting', 'This will be the default setting for users to start viewing the listings.', 'English', 'tooltip', 'en'),
(NULL, 'listings_sorting_type', 'Ascending or Descending settings will determine by preference.', 'English', 'tooltip', 'en'),
(NULL, 'expiration_period', 'If a listing is not paid or subscription expires, the number of days before action below is taken.', 'English', 'tooltip', 'en'),
(NULL, 'expiration_action', 'When the days allowed above expire, this setting will determine what action is to be taken. Default is Nothing.', 'English', 'tooltip', 'en'),
(NULL, 'mail_function', 'The Mail Method to send emails.', 'English', 'tooltip', 'en'),
(NULL, 'mimetype', 'Determines whether you want to send text or html emails (templates located in the Email Template tab to the left).', 'English', 'tooltip', 'en'),
(NULL, 'sendmail_path', 'Default is /usr/bin/sendmail', 'English', 'tooltip', 'en'),
(NULL, 'smtp_server', 'That would be Ex. (smtp.yourdomain.com)', 'English', 'tooltip', 'en'),
(NULL, 'smtp_user', 'The username is specified with your email/hosting provider.', 'English', 'tooltip', 'en'),
(NULL, 'smtp_password', 'Password for the username above.', 'English', 'tooltip', 'en'),
(NULL, 'resend_confirmation_email', 'Resend confirmation email', 'English', 'admin', 'en'),
(NULL, 'confirmation_resent', 'Confirmation email resent.', 'English', 'admin', 'en'),
(NULL, 'categories_display_type', 'Defines categories display type.<br />\r\nExample:<br />\r\n<pre>Horizontal:\r\na b c d\r\ne f g h\r\nVertical:\r\na c e g \r\nb d f h</pre>', 'English', 'tooltip', 'en'),
(NULL, 'item', 'Item', 'English', 'admin', 'en'),
(NULL, 'categories_icon_notif', 'Create and upload images to "uploads/category-icons" folder to be able choose your own category icons.', 'English', 'admin', 'en'),
(NULL, 'remove_reason', 'Remove reason', 'English', 'admin', 'en');
UPDATE `{prefix}language` SET `value` = '<p>Below is the information you submitted so far. You will be able to extend and edit this information via your member account.</p><p><span style=\"color: #F00; font-weight: bold;\">IMPORTANT!</span> Your account password has been sent to the following email address:</p>' WHERE `key` = 'thankyou_head';
UPDATE `{prefix}language` SET `category` = 'common' WHERE `key` = 'no_more_files';
ALTER TABLE `{prefix}listing_fields` CHANGE `pages` `pages` SET( 'suggest', 'edit', 'view' ) NOT NULL;
UPDATE `{prefix}listing_fields` SET `pages` = 'suggest,edit,view' WHERE `name` = 'url' OR `name` = 'title' OR `name` = 'description';
UPDATE `{prefix}listing_fields` SET `pages` = 'suggest,edit' WHERE `name` = 'email' OR `name` = 'reciprocal';
DROP TABLE IF EXISTS `{prefix}tips`;
ALTER TABLE `{prefix}plans` ADD `item` VARCHAR(50) NOT NULL DEFAULT 'listings' AFTER `mark_as`;
ALTER TABLE `{prefix}transactions` ADD `plan_title` varchar(50) NOT NULL DEFAULT '' AFTER `plan_id`;
UPDATE `{prefix}config` SET `value` = '2.3.01' WHERE `name` = 'version';
