{install:drop_tables}DROP TABLE IF EXISTS `{install:prefix}blocks`;
CREATE TABLE `{install:prefix}blocks` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(100) NOT NULL default '',
  `contents` text NOT NULL,
  `order` smallint(5) unsigned NOT NULL default '0',
  `lang` varchar(2) NOT NULL default '',
  `position` varchar(50) NOT NULL default 'left',
  `type` enum('plain','smarty','php','html') NOT NULL default 'plain',
  `plugin` varchar(50) NOT NULL default '',
  `status` enum('active','inactive') NOT NULL default 'active',
  `show_header` tinyint(1) NOT NULL default '0',
  `collapsible` tinyint(1) NOT NULL default '0',
  `collapsed` tinyint(1) NOT NULL default '0',
  `sticky` tinyint(1) NOT NULL default '0',
  `multi_language` tinyint(1) NOT NULL,
  `rss` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `status` (`status`)
) {install:mysql_version};

INSERT INTO `{install:prefix}blocks` (`id`, `title`, `contents`, `order`, `lang`, `position`, `type`, `plugin`, `status`, `show_header`, `sticky`, `multi_language`, `collapsible`, `rss`) VALUES
(1, 'Featured', '{if isset($featured_listings)}\r\n	{foreach from=$featured_listings item=featured_listing}\r\n		<div class="featured-listing">\r\n			<a href="{print_listing_url listing=$featured_listing}" class="countable listings title" id="lnk_{$featured_listing.id}_fea" {if $config.new_window}target="_blank"{/if}>{$featured_listing.title}</a>\r\n		</div>\r\n	{/foreach}\r\n{/if}', 2, 'en', 'left', 'smarty', '', 'active', 1, 1, 1, 1, 0),
(2, 'Partner', '{if isset($partner_listings)}\r\n	{foreach from=$partner_listings item=partner_listing}\r\n		<div class="partner-listing">\r\n			<a href="{print_listing_url listing=$partner_listing}" class="countable listings title" id="lnk_{$partner_listing.id}_par" {if $config.new_window}target="_blank"{/if}>{$partner_listing.title}</a>\r\n		</div>\r\n	{/foreach}\r\n{/if}', 1, 'en', 'top', 'smarty', '', 'active', 1, 1, 1, 1, 0),
(3, 'Statistics', '<table cellpadding="2" cellspacing="2">\r\n	{if isset($num_listings)}\r\n	<tr>\r\n		<td>{$lang.total_num_listings}</td>\r\n		<td>{$num_listings|string_format:"%d"}</td>\r\n	</tr>\r\n	{/if}\r\n	{if isset($num_categories)}\r\n		<tr>\r\n			<td>{$lang.total_num_categories}</td>\r\n			<td>{$num_categories|string_format:"%d"}</td>\r\n		</tr>\r\n	{/if}\r\n	{esynHooker name="statisticsBlock"}\r\n</table>', 4, 'en', 'right', 'smarty', '', 'active', 1, 0, 1, 0, 0),
(4, 'Accounts area', '{if $config.accounts}\r\n	<!-- accounts box start -->\r\n	{if $esynAccountInfo}\r\n		{$lang.welcome}, <strong>{$esynAccountInfo.username}</strong>!\r\n		<ul class="account-menu">\r\n			{foreach from=$menus.account item=menu}\r\n				{if $menu.name eq $smarty.const.ESYN_REALM}\r\n					<li class="active">\r\n						<div>{$menu.title}</div>\r\n					</li>\r\n				{else}\r\n					<li>\r\n						<a href="{$menu.url}"{if isset($menu.no_follow)}{$menu.no_follow}{/if}>{$menu.title}</a>\r\n					</li>\r\n				{/if}\r\n			{/foreach}\r\n\r\n			<li>\r\n				<a href="logout.php?action=logout">{$lang.logout}</a>\r\n			</li>\r\n		</ul>\r\n	{else}\r\n		<form action="{$smarty.const.ESYN_URL}login.php" method="post">\r\n			<table class="no" cellpadding="2" cellspacing="0">\r\n			<tr>\r\n				<td>{$lang.username}:<br />\r\n					<input type="text" tabindex="1" class="text" name="username" size="18" value="" />\r\n				</td>\r\n			</tr>\r\n			<tr>\r\n				<td>{$lang.password}:<br />\r\n					<input type="password" tabindex="2" class="text" name="password" size="18" value="" />\r\n				</td>\r\n			</tr>\r\n			<tr>\r\n				<td colspan="2" style="font-size: 10px;">\r\n					<input type="submit" class="button" tabindex="6" name="login" value="{$lang.login}" />\r\n					<a href="{$smarty.const.ESYN_URL}forgot.php">{$lang.forgot}</a>\r\n					<a href="{$smarty.const.ESYN_URL}register.php" rel="nofollow">{$lang.register}</a>\r\n				</td>\r\n			</tr>\r\n			</table>\r\n		</form>\r\n	{/if}\r\n	<!-- accounts box end -->\r\n{/if}', 1, 'en', 'right', 'smarty', '', 'active', 1, 1, 1, 1, 0),
(5, 'Actions', '{if isset($esyndicat_actions) && !empty($esyndicat_actions)}{foreach from=$esyndicat_actions item=action}\r\n	{assign var="action_key" value="esyndicat_action_"|cat:$action.name}\r\n\r\n	{if $action.name eq ''action_favorite''}\r\n		{if $esynAccountInfo}\r\n			{if $esynAccountInfo.id neq $listing.account_id}\r\n				{assign var="fav_array" value='',''|explode:$listing.fav_accounts_set}\r\n				{if !empty($fav_array) && in_array($esynAccountInfo.id, $fav_array)}\r\n					<a href="{if $action.url eq ''''}#{else}{$action.url}{/if}" class="esynactions_remove-favorite_{$listing.id}_{$esynAccountInfo.id}">{$lang.remove_from_favorites}</a><br />\r\n				{else}\r\n					<a href="{if $action.url eq ''''}#{else}{$action.url}{/if}" class="esynactions_add-favorite_{$listing.id}_{$esynAccountInfo.id}">{$lang.add_to_favorites}</a><br />\r\n				{/if}\r\n			{/if}					\r\n		{/if}\r\n	{else}\r\n		<a href="{if $action.url eq ''''}#{else}{$action.url}{/if}" class="esynactions_{$action.name|replace:"_":"-"}_{$listing.id}_{$listing.url}">{$lang.$action_key}</a><br />\r\n	{/if}\r\n{/foreach}{/if}', 4, 'en', 'right', 'smarty', '', 'active', 1, 1, 1, 0, 0),
(6, 'Latest Comments', '{if isset($latest_comments)}\n	{foreach from=$latest_comments item=comment name=latest_comments}\n		<div class="posted">\n			{print_img full=true fl="user.png" alt=$lang.comment_author}<strong>{$comment.author|escape:"html"}</strong> /  {print_img full=true fl="calendar.png" alt=$lang.calendar} {$comment.date|date_format:$config.date_format}\n		</div>\n		{if $config.html_comments}\n			<div class="comment">{$comment.body|truncate:100}<br /></div>\n		{else}\n			<div class="comment">{$comment.body|escape:"html"|truncate:100}<br /></div>\n		{/if}\n		<div style="float:right;"><a href="{print_listing_url listing=$comment.listing details=true}">{$lang.view_listing}</a></div>\n		<div style="clear:both;"></div>\n		{if !$smarty.foreach.latest_comments.last}<hr />{/if}\n	{/foreach}\n{/if}', 5, 'en', 'right', 'smarty', 'comments', 'active', 1, 1, 1, 0, 0),
(7, 'Comments', '{include file=$smarty.const.ESYN_PLUGINS|cat:"comments/templates/comments.tpl"}', 5, 'en', 'bottom', 'smarty', 'comments', 'active', 1, 0, 1, 0, 0);

