{install:drop_tables}DROP TABLE IF EXISTS `{install:prefix}config`;
CREATE TABLE `{install:prefix}config` (
  `id` int(4) NOT NULL auto_increment,
  `group_name` varchar(50) NOT NULL DEFAULT '',
  `name` varchar(100) NOT NULL default '',
  `value` text NOT NULL,
  `multiple_values` text NOT NULL,
  `type` enum('text','textarea','checkbox','radio','select','divider','hidden','password','image') NOT NULL default 'text',
  `description` text NOT NULL,
  `plugin` varchar(50) NOT NULL DEFAULT '',
  `editor` enum('0','1') NOT NULL default '0',
  `order` float NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `name` (`name`),
  KEY `type` (`type`)
) {install:mysql_version};

INSERT INTO `{install:prefix}config` (`group_name`, `name`, `value`, `multiple_values`, `type`, `description`, `plugin`, `editor`, `order`) VALUES
('', 'htaccessfile_0', '# Uncomment next line if you get 404 error on accounts page\r\n# Options -MultiViews\r\n<IfModule mod_rewrite.c>\r\n# enable mod_rewrite\r\nRewriteEngine on\r\n\r\n', '', 'hidden', 'htaccess top section', '', '0', 0),
('', 'htaccessfile_1', '# SECTION 1\r\n# correct urls for yahoo bot\r\nRewriteCond %{REQUEST_URI} !\\..+$\r\nRewriteCond %{REQUEST_URI} !/$\r\nRewriteRule (.*) %{REQUEST_URI}/ [R=301,L]\r\n\r\n# mod_rewrite rules for plugins\r\nRewriteRule ^mod/(.*)/$ controller.php?plugin=$1 [QSA,L]\r\nRewriteRule ^mod/(.*)/(.*)/$ controller.php?plugin=$1&file=$2 [QSA,L]\r\nRewriteRule ^mod/(.*)/(.*).html$ controller.php?plugin=$1&file=$2 [QSA,L]\r\n\r\n# mod_rewrite rules for view account page\r\nRewriteRule ^accounts/$ accounts.php [QSA,L]\r\nRewriteRule ^accounts/(.*)/$ accounts.php?alpha=$1 [QSA,L]\r\nRewriteRule ^accounts/(.*).html$ view-account.php?account=$1 [QSA,L]\r\n\r\nRewriteRule ^sitemap.xml$ tmp/sitemap/google/sitemap.xml [QSA,L]\r\n\r\nRewriteRule ^sitemap([0-9]+).xml$ tmp/sitemap/google/sitemap$1.xml [QSA,L]\r\nRewriteRule ^sitemap_index.xml$ tmp/sitemap/google/sitemap_index.xml [QSA,L]\r\nRewriteRule ^urllist.txt$ tmp/sitemap/yahoo/urllist.txt [QSA,L]', '', 'hidden', 'htaccess section 1', '', '0', 0),
('', 'htaccessfile_2', '# SECTION 2\r\n# mod_rewrite rules for ROOT category\r\nRewriteRule ^index([0-9]+).html$ index.php?category=0&page=$1 [QSA,L]\r\n\r\n', '', 'hidden', 'htaccess section 2', '', '0', 0),
('', 'htaccessfile_3', '# SECTION 3\r\n# mod_rewrite rules for categories pages with HTML path option disable\r\nRewriteRule ^(.*)/$ index.php?category=$1 [QSA,L]\r\nRewriteRule ^(.*)/index([0-9]+).html$ index.php?category=$1&page=$2 [QSA,L]\r\n\r\n', '', 'hidden', 'htaccess section 3', '', '0', 0),
('', 'htaccessfile_4', '# SECTION 4\r\n# mod_rewrite rule for suggest listing page\r\nRewriteRule report-listing.php$ report-listing.php [QSA,L]\r\n\r\n', '', 'hidden', 'htaccess section 4', '', '0', 0),
('', 'htaccessfile_5', '# SECTION 5\r\nRewriteRule ^([a-z]+)-listings.html$ listings.php?view=$1 [QSA,L]\r\nRewriteRule ^([a-z]+)-listings([0-9]+).html$ listings.php?view=$1&page=$2 [QSA,L]\r\n\r\n', '', 'hidden', 'htaccess section 5', '', '0', 0),
('', 'htaccessfile_6', '# SECTION 6\r\n# mod_rewrite rules for view listing page\r\nRewriteRule ^([^/]+)-l([0-9]+).html$ view-listing.php?cat=&title=$1&id=$2 [QSA,L]\r\nRewriteRule ^(.*)/([^/]+)-l([0-9]+).html$ view-listing.php?cat=$1&title=$2&id=$3 [QSA,L]\r\n\r\n', '', 'hidden', 'htaccess section 6', '', '0', 0),
('', 'htaccessfile_7', '# SECTION 7\r\n# mod_rewrite rules for additional pages\r\nRewriteRule ^p/(.*).html$ page.php?name=$1 [QSA,L]\r\n\r\n', '', 'hidden', 'htaccess section 7', '', '0', 0),
('', 'htaccessfile_8', '# SECTION 8\r\n# mod_rewrite rules for error pages\r\nRewriteRule ^([0-9]+).htm$ error.php?error=$1 [QSA,L]\r\n\r\n', '', 'hidden', 'htaccess section 8', '', '0', 0),
('', 'htaccessfile_9', '# SECTION 9\r\n# mod_rewrite rules for suggest category page\r\nRewriteRule ^suggest-category-([0-9]+).html$ suggest-category.php?id=$1 [QSA,L]\r\n\r\n', '', 'hidden', 'htaccess section 9', '', '0', 0),
('', 'htaccessfile_10', '# SECTION 10\r\nRewriteRule ^LICENSE.htm$ LICENSE.htm [QSA,L]\r\n\r\n', '', 'hidden', 'htaccess section 10', '', '0', 0),
('', 'htaccessfile_11', '# SECTION 11\r\n# mod_rewrite rules for categories pages\r\nRewriteRule ^(.*)_([0-9]+).html$ index.php?category=$1&page=$2 [QSA,L]\r\nRewriteRule ^(.*).html?(.*)$ index.php?category=$1&$2 [QSA,L]\r\nRewriteRule ^(.*).html$ index.php?category=$1 [QSA,L]\r\n</IfModule>\r\n\r\n', '', 'hidden', 'htaccess section 11', '', '0', 0),
('', 'htaccessfile_12', '# SECTION 12\r\nErrorDocument 500 500.htm\r\nErrorDocument 404 404.htm\r\nErrorDocument 403 403.htm\r\nErrorDocument 401 401.htm', '', 'hidden', 'htaccess section 12', '', '0', 0),
('accounts', '', 'General', '1', 'divider', '', '', '0', 1),
('accounts', 'accounts', '1', '''1'',''0''', 'radio', 'Accounts', '', '0', 2),
('accounts', 'accounts_autoapproval', '0', '''1'',''0''', 'radio', 'Accounts Auto Approval', '', '0', 3),
('listings', 'accounts_registered', '1', '''1'',''0''', 'radio', 'Allow submissions for guests', '', '0', 4),
('captcha', '', 'General', '1', 'divider', '', '', '0', 1),
('captcha', 'captcha', '1', '''1'',''0''', 'radio', 'Captcha', '', '0', 2),
('captcha', 'captcha_name', 'kcaptcha', 'kcaptcha', 'select', 'Name of CAPTCHA', '', '0', 3),
('captcha', 'captcha_preview', '', '', 'text', 'Captcha preview', '', '0', 3.1),
('captcha', 'kcaptcha', 'KCAPTCHA configuration', '', 'divider', 'KCAPTCHA configuration', 'kcaptcha', '0', 119.1),
('captcha', 'captcha_case_sensitive', '1', '1,0', 'radio', 'Case sensitive', 'kcaptcha', '0', 120.1),
('captcha', 'captcha_num_chars', '5', '', 'text', 'Number of characters', 'kcaptcha', '0', 121.1),
('categories', '', 'General', '1', 'divider', '', '', '0', 0),
('categories', 'suggest_category', '1', '''1'',''0''', 'radio', 'Allow category submission', '', '0', 1),
('categories', 'use_html_path', '0', '''1'',''0''', 'radio', 'Use .html extension in category URL', '', '0', 2),
('categories', 'related', '1', '''1'',''0''', 'radio', 'Related categories display', '', '0', 3),
('categories', 'neighbour', '1', '''1'',''0''', 'radio', 'Neighbour categories display', '', '0', 4),
('categories', 'show_children_listings', '0', '''1'',''0''', 'radio', 'Show subcategories listings in the parents', '', '0', 4.5),
('categories', 'categories_order', 'title', '''title'',''order''', 'select', 'Categories sorting', '', '0', 5),
('categories', 'num_categories_cols', '3', '', 'text', 'Number of columns', '', '0', 6),
('categories', 'num_listings_display', '1', '''1'',''0''', 'radio', 'Listings count indicator', '', '0', 7),
('categories', 'subcats_display', '3', '', 'text', 'Number of subcategories', '', '0', 8),
('categories', 'num_cats_for_search', '5', '', 'text', 'Number of categories on the search page', '', '0', 8),
('categories', 'categories_tree_type', 'tree', '''tree'',''dropdown'',''simple dropdown''', 'select', 'Category selection method', '', '0', 5.1),
('categories', 'categories_display_type', 'vertical', '''vertical'',''horizontal''', 'select', 'Categories display type', '', '0', 4.9),
('categories', 'categories_icon_width', '32', '', 'text', 'Category icon width', '', '0', 8.1),
('categories', 'categories_icon_height', '32', '', 'text', 'Categories icon height', '', '0', 8.2),
('cronjob', '', 'Check-UP CRON', '1', 'divider', '', '', '0', 52),
('cronjob', 'cron_recip', '0', '''1'',''0''', 'radio', 'Cron for checking reciprocal listings', '', '0', 53),
('cronjob', 'cron_broken', '0', '''1'',''0''', 'radio', 'Gets listing status (checking for broken listings)', '', '0', 54),
('cronjob', 'cron_pagerank', '0', '''1'',''0''', 'radio', 'Cron for listings pagerank update', '', '0', 55),
('cronjob', 'cron_num_listings', '10', '', 'text', 'Number of listings to check in one run', '', '0', 56),
('cronjob', 'cron_check_interval', '1', '', 'text', 'Check interval (in days)', '', '0', 57),
('cronjob', '', 'CRON email reports', '1', 'divider', '', '', '0', 58),
('cronjob', 'cron_report_job', '0', '''1'',''0''', 'radio', 'CRON should send email each CronJob', '', '0', 59),
('cronjob', 'cron_report_job_extra', '0', '''1'',''0''', 'radio', 'Include list of listing URLs (each CronJob)', '', '0', 60),
('cronjob', 'cron_report_cycle', '0', '''1'',''0''', 'radio', 'CRON should send email after all listings will be checked', '', '0', 61),
('cronjob', 'cron_report_cycle_extra', '0', '''1'',''0''', 'radio', 'Include list of listing URLs (each CronCycle)', '', '0', 62),
('cronjob', '', 'Backup CRON', '1', 'divider', '', '', '0', 67),
('cronjob', 'cron_backup', '0', '''1'',''0''', 'radio', 'Backup cron functionality', '', '0', 68),
('cronjob', 'cron_backup_archive', '0', '''1'',''0''', 'radio', 'Archive Data (Zlib PHP requires)', '', '0', 69),
('cronjob', 'cron_backup_interval', '30', '', 'text', 'Make backup each [..] day(s)', '', '0', 70),
('cronjob', 'cron_backup_last_time', '', '', 'hidden', '', '', '0', 71),
('cronjob', 'cron', '1', '', 'hidden', '', '', '0', NULL),
('general', '', 'Path & URLs', '1', 'divider', '', '', '0', 1),
('general', 'version', '{config_version}', '', 'hidden', '', '', '0', 2),
('general', 'site', 'eSyndiCat Directory', '1', 'text', 'Site title', '', '0', 3),
('general', 'site_logo', '', '', 'image', 'Site Logo', '', '0', 3.1),
('general', 'site_main_content', '', '', 'textarea', 'Index page content', '', '1', 3.13),
('general', 'site_description', '', '', 'textarea', 'Index META description', '', '0', 3.2),
('general', 'site_keywords', '', '', 'text', 'Index META keywords', '', '0', 3.3),
('general', 'backup', 'backup/', '1', 'text', 'Directory for database backups', '', '0', 5),
('general', '', 'Emails', '1', 'divider', '', '', '0', 7),
('general', 'site_email', '{install:email}', '1', 'text', 'Email', '', '0', 8),
('general', 'bugs_email', '{install:email}', '1', 'text', 'Bugs email', '', '0', 9),
('general', 'tmpl', 'cleancss', '', 'hidden', 'Your skin template', '', '0', 12),
('general', 'admin_tmpl', 'default', '1', 'hidden', 'Your admin skin template', '', '0', 12.1),
('general', '', 'Regional', '1', 'divider', '', '', '0', 13),
('general', 'lang', '{install:lang}', '1', 'select', 'Script language', '', '0', 14),
('general', 'charset', 'UTF-8', '1', 'text', 'Default charset for pages', '', '0', 15),
('general', 'date_format', '%b %e, %Y', '', 'text', 'Date format', '', '0', 15),
('general', '', 'General', '1', 'divider', '', '', '0', 16),
('general', 'suffix', ':: Powered by eSyndiCat', '1', 'text', 'Suffix for page titles', '', '0', 3.05),
('general', 'title_breadcrumb', '0', '''1'',''0''', 'radio', 'Full path to category in title', '', '0', 18),
('general', 'language_switch', '0', '''1'',''0''', 'radio', 'Language switching', '', '0', 19),
('general', 'mod_rewrite', '1', '''1'',''0''', 'radio', 'Apache mod_rewrite module', '', '0', 20),
('general', 'display_frontend', '1', '''1'',''0''', 'radio', 'Display FrontEnd', '', '0', 23),
('general', 'underconstruction', 'We are sorry. Our site is under construction.', '', 'textarea', 'Under construction message', '', '0', 24),
('general', 'esyndicat_news_url', 'http://blog.intelliants.com/?view=rss', '', 'hidden', '', '', '0', 0),
('general', 'esyndicat_new_plugins_url', 'http://tools.esyndicat.com/new_plugins.php', '', 'hidden', '', '', '0', 0),
('general', 'esyndicat_block_positions', 'left,right,top,center,bottom,user1,user2,verybottom,verytop,topbanner', '', 'hidden', 'eSyndiCat Block Positions', '', '0', 0),
('general', 'ckeditor_color', '#F00', '', 'hidden', 'CKEditor color', '', '0', 0),
('general', 'esyndicat_menu_type', 'inventory,main,bottom,account', '', 'hidden', 'menu type', '', '0', 0),
('general', 'display_twitter', '1', '', 'hidden', 'eSyndiCat Twitter Block', '', '0', '0'),
('general', 'config_keys', 'recaptcha_publickey,recaptcha_privatekey,sendmail_path,smtp_secure_connection,smtp_server,smtp_user,smtp_password', '', 'hidden', '', '', '0', 0),
('general', 'default_categories_icon', 'templates/common/img/category_icons/category_icon.gif', '', 'hidden', 'Default categories icon path', '', '0', 0),
('listings', '', 'General', '1', 'divider', '', '', '0', 1),
('listings', 'allow_listings_submission', '1', '''1'',''0''', 'radio', 'Allow listing submission', '', '0', 2),
('listings', 'auto_approval', '0', '''1'',''0''', 'radio', 'Auto approval on submission', '', '0', 3),
('listings', 'new_window', '0', '''1'',''0''', 'radio', 'Open listings in a new window', '', '0', 4),
('listings', 'forward_to_listing_details', '1', '''1'',''0''', 'radio', 'Forward to listing details', '', '0', 5),
('listings', 'pagerank', '1', '''1'',''0''', 'radio', 'Google PageRank display', '', '0', 6),
('listings', 'thumbshot', '1', '''1'',''0''', 'radio', 'Display thumbshots', '', '0', 7),
('listings', 'num_index_listings', '10', '', 'text', 'Number of listings per page', '', '0', 8),
('listings', 'num_get_listings', '10', '', 'text', 'Number of listings(Top, New, Popular)', '', '0', 8.5),
('listings', 'num_featured_display', '3', '', 'text', 'Number of listings in Featured Box', '', '0', 9),
('listings', 'num_partner_display', '3', '', 'text', 'Number of listings in Partners Box', '', '0', 10),
('listings', '', 'Sorting', '1', 'divider', '', '', '0', 11),
('listings', 'visitor_sorting', '1', '''1'',''0''', 'radio', 'Allow listing ordering for visitors', '', '0', 12),
('listings', 'listings_sorting', 'alphabetic', '''alphabetic'',''date'',''clicks'',''rank''', 'select', 'Listings order by', '', '0', 13),
('listings', 'listings_sorting_type', 'ascending', '''ascending'',''descending''', 'select', 'Listings order type', '', '0', 14),
('listings', '', 'Expiration Date', '1', 'divider', '', '', '0', 15),
('listings', 'expiration_period', '', '', 'text', 'Listing expiration period (days)', '', '0', 16),
('listings', 'expiration_action', '', '', 'text', 'Listing expiration action', '', '0', 17),
('listings', 'broken_listings_report', '1', '''1'',''0''', 'radio', 'Broken listings report', '', '0', 7.1),
('listing_checking', '', 'Broken Checking', '', 'divider', '', '', '0', 30.6),
('listing_checking', 'listing_check', '0', '''1'',''0''', 'radio', 'Checking for broken listings', '', '0', 31),
('listing_checking', 'broken_visitors', '1', '''1'',''0''', 'radio', 'Disabled in admin panel', '', '0', 31.5),
('listing_checking', 'http_headers', '301,302,200', '', 'text', 'Correct HTTP headers', '', '0', 31.55),
('listing_checking', '', 'Reciprocal Checking', '', 'divider', '', '', '0', 31.6),
('listing_checking', 'reciprocal_check', '0', '''1'',''0''', 'radio', 'Reciprocal listing checking', '', '0', 32),
('listing_checking', 'reciprocal_required_only_for_free', '0', '''1'',''0''', 'radio', 'Reciprocal required for free listings', '', '0', 32.1),
('listing_checking', 'reciprocal_domain', '1', '''1'',''0''', 'radio', 'Domain sensitive', '', '0', 32.1),
('listing_checking', 'reciprocal_text', '{install:url}', '', 'text', 'Reciprocal checking for the following URL', '', '0', 56),
('listing_checking', 'recip_featured', '0', '''1'',''0''', 'radio', 'Make featured', '', '0', 56.5),
('listing_checking', 'reciprocal_visitors', '1', '''1'',''0''', 'radio', 'Checked in admin panel', '', '0', 99.95),
('listing_checking', '', 'Duplicate Checking', '', 'divider', '', '', '0', 100),
('listing_checking', 'duplicate_checking', '0', '''1'',''0''', 'radio', 'Duplicate listing checking', '', '0', 101),
('listing_checking', 'duplicate_type', 'domain', '''exact'',''domain'',''contain''', 'select', 'Duplicate checking type', '', '0', 102),
('listing_checking', 'duplicate_visitors', '1', '''1'',''0''', 'radio', 'Disabled in admin panel', '', '0', 103),
('listing_checking', 'reciprocal_label', 'To validate the reciprocal link please include the following HTML code in the page at the URL specified above, before submitting this form:', '', 'textarea', 'Reciprocal text on the suggest listing page', '', '0', 99.96),
('listing_checking', 'reciprocal_code', '', '', 'textarea', 'Reciprocal code', '', '0', 99.97),
('mail', '', 'Mail type', '1', 'divider', '', '', '0', 1),
('mail', 'mail_function', 'php mail', '''php mail'',''sendmail'',''smtp''', 'select', 'Mail method', '', '0', 2),
('mail', 'mimetype', 'html', '''html'',''plaintext''', 'select', 'Mime-Type', '', '0', 3),
('mail', '', 'Sendmail Configuration', '', 'divider', '', '', '0', 4),
('mail', 'sendmail_path', '/usr/bin/sendmail', '', 'text', 'Path to sendmail ', '', '0', 5),
('mail', '', 'SMTP Configuration', '', 'divider', '', '', '0', 6),
('mail', 'smtp_secure_connection', '', ''''',''SSL'',''TSL''', 'select', 'Use secure connection', '', '0', 7),
('mail', 'smtp_server', '', '', 'text', 'SMTP Server', '', '0', 8),
('mail', 'smtp_port', '25', '', 'text', 'SMTP Port', '', '0', 8.1),
('mail', 'smtp_user', '', '', 'text', 'SMTP Server Username', '', '0', 9),
('mail', 'smtp_password', '', '', 'password', 'SMTP Server Password', '', '0', 10),
('email_templates', '', 'Listing Submitted', '', 'divider', '', '', '0', 0.2),
('email_templates', 'listing_submit', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 0.3),
('email_templates', 'listing_submit_subject', 'Listing was submitted to {own_site}', '', 'text', 'Subject', '', '0', 0.4),
('email_templates', 'listing_submit_body_html', '<h3>\r\n	Dear Sir/Madam,</h3>\r\n<p>\r\n	We are glad to inform you that a link to {your_site_url} has been submitted to <em><a href="{own_dir_url}">{own_site}</a></em> ({own_dir_url}). Your submission will be reviewed within 24 hours.</p>\r\n<p>\r\n	After approval and activation, your URL will be listed at:</p>\r\n<p>\r\n	<a href="{dir_listing}"><i>{dir_listing}</i></a></p>\r\n<p>\r\n	Now, please add a link to <em><a href="{own_dir_url}">{own_site}</a></em> to any of your site&#39;s pages.</p>\r\n<p>\r\n	Please use the code below:</p>\r\n<pre><a href="{own_url}">{own_site}</a></pre>\r\n<p>\r\n	OR use the following information</p>\r\n<pre>TITLE: <em>{own_site}</em>\r\nURL: <em>{own_url}</em>\r\nDESCRIPTION: <em>your site description</em>\r\n</pre>\r\n<p>\r\n	All the listings in our directory are direct, so they will improve your listing popularity.</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 0.5),
('email_templates', 'listing_submit_body_plaintext', 'Dear Sir/Madam,\r\n \r\nWe are glad to inform you that a link to {your_site_url}\r\nhas been submitted to {own_site} ({own_dir_url}).\r\nYour submission will be reviewed within 24 hours.\r\n  \r\nAfter approval and activation, your URL will be listed at: \r\n{dir_listing}\r\n  \r\nNow, please add a link to {own_site} to any of your site''s pages.\r\n\r\nPlease use the code below:\r\n------------------------------------\r\n<a href="{own_url}">{own_site}</a>\r\n------------------------------------\r\n\r\nOR use the following information\r\n------------------------------------\r\nTITLE: {own_site}\r\nURL: {own_url}\r\nDESCRIPTION: your site description\r\n\r\nAll the listings in our directory are direct, so they will improve your listing popularity.\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 0.51),
('email_templates', '', 'Listing Approved', '', 'divider', '', '', '0', 0.6),
('email_templates', 'listing_approve', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 0.65),
('email_templates', 'listing_approve_subject', 'Listing was approved in {own_site}', '', 'text', 'Subject', '', '0', 0.68),
('email_templates', 'listing_approve_body_html', '<h3>\r\n	Dear Sir/Madam,</h3>\r\n<p>\r\n	Congratulations! Your listing {your_site_url} has been approved for <em><a href="{own_dir_url}">{own_site}</a></em>. You can view it at:</p>\r\n<p>\r\n	<em><a href="{dir_listing}">{dir_listing}</a></em></p>\r\n<p>\r\n	If you have not placed reciprocal listing to <em><a href="{own_dir_url}">{own_site}</a></em> yet, please add a listing to {own_url} to any of your site&#39;s pages.</p>\r\n<p>\r\n	Please use the code below:</p>\r\n<pre><a href="{own_url}">{own_site}</a></pre>\r\n<p>\r\n	OR use the following information</p>\r\n<pre>TITLE: <em>{own_site}</em>\r\nURL: <em>{own_url}</em>\r\nDESCRIPTION: <em>your site description</em>\r\n</pre>\r\n<p>\r\n	All the listings in our directory are direct, so they will improve your listing popularity.</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 0.7),
('email_templates', 'listing_approve_body_plaintext', 'Dear Sir/Madam,\r\n  \r\nCongratulations! Your listing {your_site_url} has been approved for {own_site}.\r\nYou can view it at {dir_listing}.\r\n  \r\nIf you have not placed reciprocal listing to {own_site} yet,\r\nplease add a listing to {own_url} to any of your site''s pages.\r\n\r\nPlease use the code below:\r\n------------------------------------\r\n<a href="{own_url}">{own_site}</a>\r\n------------------------------------\r\n\r\nOR use the following information\r\n------------------------------------\r\nTITLE: {own_site}\r\nURL: {own_url}\r\nDESCRIPTION: site description\r\n------------------------------------\r\n\r\nAll the listings in our directory are direct, so they will improve your listing popularity.\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 0.7),
('email_templates', '', 'Listing Disapproved', '', 'divider', '', '', '0', 0.71),
('email_templates', 'listing_disapprove', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 0.72),
('email_templates', 'listing_disapprove_subject', 'Listing was disapproved in {own_site}', '', 'text', 'Subject', '', '0', 0.73),
('email_templates', 'listing_disapprove_body_html', '<h3>\r\n	Dear Sir/Madam,</h3>\r\n<p>\r\n	Your listing {your_site_url} has been disapproved in<em> <a href="{own_dir_url}">{own_site}</a></em>.</p>\r\n<p>\r\n	If you have questions, please feel free to ask us.</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 0.74),
('email_templates', 'listing_disapprove_body_plaintext', 'Dear Sir/Madam,\r\n\r\nYour listing {your_site_url} has been disapproved in {own_site} Listings Directory.\r\n\r\nIf you have questions, please feel free to ask us.\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 0.741),
('email_templates', '', 'Listing Moved', '', 'divider', '', '', '0', 56.8),
('email_templates', 'listing_move', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 56.9),
('email_templates', 'listing_move_subject', 'Listing was moved in {own_site}', '', 'text', 'Subject', '', '0', 56.95),
('email_templates', 'listing_move_body_html', '<h3>\r\n	Dear Sir/Madam,</h3>\r\n<p>\r\n	We are glad to inform you, that your listing to site {your_site_url} was moved into another category.</p>\r\n<p>\r\n	This is the new location of your listing:</p>\r\n<p>\r\n	<em><a href="{dir_listing}">{dir_listing}</a></em></p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 57),
('email_templates', 'listing_move_body_plaintext', 'Dear Sir/Madam,\r\n\r\nWe are glad to inform you, that your listing to site {your_site_url} was moved into another category. \r\nThis is the new location of your listing:\r\n\r\n{dir_listing}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 57.1),
('email_templates', '', 'Listing Modified', '', 'divider', '', '', '0', 57.5),
('email_templates', 'listing_modify', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 57.6),
('email_templates', 'listing_modify_subject', 'Listing was modified in {own_site}', '', 'text', 'Subject', '', '0', 57.7),
('email_templates', 'listing_modify_body_html', '<h3>\r\n	Dear Sir/Madam,</h3>\r\n<p>\r\n	We are glad to inform you, that your listing to site {your_site_url} was modified.</p>\r\n<p>\r\n	These are the new attributes of your listing:</p>\r\n<p>\r\n	Title: <em>{your_site_title}</em><br />\r\n	URL: <em>{your_site_url}</em><br />\r\n	Description: <em>{your_site_desc}</em><br />\r\n	Email: <em>{your_site_email}</em><br />\r\n	Rank: <em>{your_site_rank}</em><br />\r\n	Status: <em>{your_site_status}</em></p>\r\n<p>\r\n	You can view your listing here:</p>\r\n<p>\r\n	<em><a href="{dir_listing}">{dir_listing}</a></em></p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '1', 'textarea', 'HTML Body', '', '1', 57.8),
('email_templates', 'listing_modify_body_plaintext', 'Dear Sir/Madam,\r\n\r\nWe are glad to inform you, that your listing to site {your_site_url} was modified.\r\nThese are the new attributes of your listing:\r\n\r\nTitle: {your_site_title}\r\nURL: {your_site_url}\r\nDescription: {your_site_desc}\r\nEmail: {your_site_email}\r\nRank: {your_site_rank}\r\nStatus: {your_site_status}\r\n\r\nYou can view your listing here:\r\n{dir_listing}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '1', 'textarea', 'Email Body', '', '0', 57.81),
('email_templates', '', 'Listing Banned', '', 'divider', '', '', '0', 58),
('email_templates', 'listing_reject', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 58.5),
('email_templates', 'listing_reject_subject', 'Listing was banned in {own_site}', '', 'text', 'Subject', '', '0', 58.6),
('email_templates', 'listing_reject_body_html', '<h3>\r\n	Dear Sir/Madam,</h3>\r\n<p>\r\n	Your listing to {your_site_url} has been banned in <em><a href="{own_dir_url}">{own_site}</a></em>.</p>\r\n<p>\r\n	If you have questions, please feel free to ask us.</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '1', 'textarea', 'HTML Body', '', '1', 59),
('email_templates', 'listing_reject_body_plaintext', 'Dear Sir/Madam,\r\n\r\nListing to {your_site_url} in our directory has been banned.\r\n\r\nIf you have questions, please feel free to ask us.\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '1', 'textarea', 'Email Body', '', '0', 59.1),
('email_templates', '', 'Listing Deleted', '', 'divider', '', '', '0', 59.9),
('email_templates', 'listing_delete', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 60),
('email_templates', 'listing_delete_subject', 'Listing was deleted from {own_site}', '', 'text', 'Subject', '', '0', 61),
('email_templates', 'listing_delete_body_html', '<h3>\r\n	Dear Sir/Madam,</h3>\r\n<p>\r\n	Your listing {your_site_url} has been deleted from</p>\r\n<p>\r\n	<em><a href="{dir_listing}">{dir_listing}</a></em></p>\r\n<p>\r\n	category, probably because you did not place reciprocal listing(s) to <em><a href="{own_dir_url}">{own_site}</a></em>. To see your listing again, please add a listing to our site and inform us.</p>\r\n<p>\r\n	<em>{reason}</em></p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '1', 'textarea', 'HTML Body', '', '1', 62),
('email_templates', 'listing_delete_body_plaintext', 'Dear Sir/Madam,\r\n\r\nYour listing {your_site_url} has been deleted from {dir_listing} category,\r\nprobably because you did not place reciprocal listing(s) to {own_site}. \r\nTo see your listing again, please add a listing to our site and inform us.\r\n\r\n{reason}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '1', 'textarea', 'Email Body', '', '0', 62.1),
('email_templates', '', 'Listing Added', '', 'divider', '', '', '0', 62.5),
('email_templates', 'listing_admin_add', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 63),
('email_templates', 'listing_admin_add_subject', 'Listing was added to {own_site}', '', 'text', 'Subject', '', '0', 64),
('email_templates', 'listing_admin_add_body_html', '<h3>\r\n	Dear Sir/Madam,</h3>\r\n<p>\r\n	We are glad to inform you that a listing to {your_site_url} has been added to <em><a href="{own_dir_url}">{own_site}</a></em> ({own_dir_url}).</p>\r\n<p>\r\n	These are the attributes of your listing:<br />\r\n	Title: <em>{your_site_title}</em><br />\r\n	URL: <em>{your_site_url}</em><br />\r\n	Description:<em> {your_site_desc}</em><br />\r\n	Email: <em>{your_site_email}</em><br />\r\n	Rank:<em> {your_site_rank}</em></p>\r\n<p>\r\n	You can view your listing here:</p>\r\n<p>\r\n	<em><a href="{dir_listing}">{dir_listing}</a></em></p>\r\n<p>\r\n	Now, please add a listing to {own_site} to any of your site&#39;s pages.</p>\r\n<p>\r\n	Please use the code below:<br />\r\n	------------------------------------<br />\r\n	<a href="{own_url}">{own_site}</a><br />\r\n	------------------------------------</p>\r\n<p>\r\n	OR use the following information<br />\r\n	------------------------------------<br />\r\n	TITLE: <em>{own_site}</em><br />\r\n	URL: <em>{own_url}</em><br />\r\n	DESCRIPTION: <em>your site description</em></p>\r\n<p>\r\n	All the listings in our directory are direct, so they will improve your listing popularity.</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'Email that is sent when admin adds listing', '', '1', 65),
('email_templates', 'listing_admin_add_body_plaintext', 'Dear Sir/Madam,\r\n \r\nWe are glad to inform you that a listing to {your_site_url} has been added to {own_site} Listings Directory ({own_dir_url}).\r\n  \r\nThese are the attributes of your listing:\r\nTitle: {your_site_title}\r\nURL: {your_site_url}\r\nDescription: {your_site_desc}\r\nEmail: {your_site_email}\r\nRank: {your_site_rank}\r\nStatus: {your_site_status}\r\n\r\nYou can view your listing here {dir_listing}\r\n\r\nNow, please add a listing to {own_site} to any of your site''s pages.\r\n\r\nPlease use the code below:\r\n------------------------------------\r\n<a href="{own_url}">{own_site}</a>\r\n------------------------------------\r\n\r\nOR use the following information\r\n------------------------------------\r\nTITLE: {own_site}\r\nURL: {own_url}\r\nDESCRIPTION: your site description\r\n\r\nAll the listings in our directory are direct, so they will improve your listing popularity.\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 65.1),
('email_templates', '', 'Account Registration', '', 'divider', '', '', '0', 66.5),
('email_templates', 'register_account', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 66.6),
('email_templates', 'register_account_subject', 'Thanks for registration at {own_site}', '', 'text', 'Subject: ', '', '0', 67),
('email_templates', 'register_account_body_html', '<h3>\r\n	Dear Sir/Madam,</h3>\r\n<p>\r\n	Thanks for your registration at <em><a href="{own_dir_url}">{own_site}</a></em>. Here is information you should use in order to login:</p>\r\n<p>\r\n	Your username: <strong>{account_username}</strong><br />\r\n	Your password: <strong>{account_pwd}</strong><br />\r\n	Your activation key: {key}</p>\r\n<p>\r\n	To activate your account go to<em> <a href="{own_site}register.php?user={account_username_url}&amp;key={key}&amp;action=confirm">{own_site}register.php?user={account_username_url}&amp;key={key}&amp;action=confirm</a></em></p>\r\n<p>\r\n	You may change your password later by editing your personal attributes in your account area.</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 68),
('email_templates', 'register_account_body_plaintext', 'Dear Sir/Madam,\r\n\r\nThanks for your registration at {own_site}. Here is information you should use in order to login:\r\n\r\nYour username: {account_username}\r\nYour password: {account_pwd}\r\n\r\nYour activation key: {key}\r\n\r\nTo activate your account go to {own_site}register.php?user={account_username_url}&key={key}&action=confirm\r\n\r\nYou may change your password later by editing your personal attributes in your account area.\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 68),
('email_templates', '', 'Account Registration Admin Notification', '', 'divider', '', '', '0', 68.01),
('email_templates', 'account_register', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 68.02),
('email_templates', 'account_register_subject', 'Account was registered to {own_site}', '', 'text', 'Subject: ', '', '0', 68.03),
('email_templates', 'account_register_body_html', '<h3>Dear {admin_name},</h3>\r\n<p>\r\n	Account was registered to <em><a href="{own_dir_url}">{own_site}</a></em>. Please\r\ncheck it.</p>\r\n<p>\r\n	These are the attributes of the account:<br />\r\n	Username:<em>\r\n{account_username}</em><br />\r\n	Email:<em> {account_email}</em></p>\r\n<p>\r\n______________________________<br />\r\nThank you,<br />\r\n{own_site} Administration\r\nTeam<br />\r\n{own_url}<br />\r\n{own_email}</p>', '', 'textarea', 'HTML Body', '', '1', 68.04),
('email_templates', 'account_register_body_plaintext', 'Dear {admin_name},\r\n\r\nAccount was registered to {own_site} Directory. Please check it.\r\n\r\nThese are the\r\nattributes of the account:\r\nUsername: {account_username}\r\nEmail: {account_email}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 68.05),
('email_templates', '', 'Account Confirmed Admin Notification', '', 'divider', '', '', '0', 68.06),
('email_templates', 'account_confirmed', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 68.07),
('email_templates', 'account_confirmed_subject', 'Account was confirmed in {own_site}', '', 'text', 'Subject: ', '', '0', 68.08),
('email_templates', 'account_confirmed_body_html', '<h3>Dear {admin_name},</h3>\r\n<p>\r\n	Account was confirmed in <em><a href="{own_dir_url}">{own_site}</a></em>. Please\r\ncheck it.</p>\r\n<p>\r\n	These are the attributes of the account:<br />\r\n	Username:<em>\r\n{account_username}</em><br />\r\n	Email:<em> {account_email}</em><br />\r\n	Status:<em> {account_status}</em></p>\r\n<p>\r\n______________________________<br />\r\nThank you,<br />\r\n{own_site} Administration\r\nTeam<br />\r\n{own_url}<br />\r\n{own_email}</p>', '', 'textarea', 'HTML Body', '', '1', 68.09),
('email_templates', 'account_confirmed_body_plaintext', 'Dear {admin_name},\r\n\r\nAccount was confirmed in {own_site} Directory. Please check it.\r\n\r\nThese are the\r\nattributes of the account:\r\nUsername: {account_username}\r\nEmail: {account_email}\r\nStatus: {account_status}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 68.09),
('email_templates', '', 'Admin Account Registration', '', 'divider', '', '', '0', 68.1),
('email_templates', 'register_account_admin', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 69),
('email_templates', 'register_account_admin_subject', 'Thanks for registration at {own_site}', '', 'text', 'Subject: ', '', '0', 69.1),
('email_templates', 'register_account_admin_body_plaintext', 'Dear Sir/Madam,\r\n\r\nYour website {your_site_url} has been added to {own_site}.\r\n\r\nThis is the information we have added:\r\n\r\nTitle: {your_site_title}\r\nDescription: {your_site_desc}\r\nURL: {your_site_url}\r\nEmail: {your_site_email}\r\n\r\nYou can find your listing at {dir_listing}\r\n\r\nIf you would like to update your listing information or provide more complete contact information, etc, you can login using the following information\r\n\r\nYour username: {account_username}\r\nYour password: {account_pwd}\r\n\r\nLogin page: {own_site}/login.php\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 69.2),
('email_templates', 'register_account_admin_body_html', '<h3>\r\n	Dear Sir/Madam,</h3>\r\n<p>\r\n	Your website {your_site_url} has been added to {own_site}</p>\r\n<p>\r\n	This is the information we have added:</p>\r\n<p>\r\n	Title: {your_site_title}<br />\r\n	Description: {your_site_desc}<br />\r\n	URL: {your_site_url}<br />\r\n	Email: {your_site_email}</p>\r\n<p>\r\n	You can find your listing at {dir_listing}</p>\r\n<p>\r\n	If you would like to update your listing information or provide more complete contact information, etc, you can login using the following information:</p>\r\n<p>\r\n	Your username: {account_username}<br />\r\n	Your password: {account_pwd}</p>\r\n<p>\r\n	Login page: {own_site}login.php</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you,<br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>', '', 'textarea', 'HTML Body', '', '1', 69.2),
('email_templates', '', 'Submission Notification Email for Admin', '', 'divider', '', '', '0', 80),
('email_templates', 'admin_notif_subject', 'Listing was submitted to {own_site}', '', 'text', 'Email subject', '', '0', 81),
('email_templates', 'admin_notif_body_html', '<h3>\r\n	Dear {admin_name},</h3>\r\n<p>\r\n	Listing was submitted to <em><a href="{own_dir_url}">{own_site}</a></em>. Please check it.</p>\r\n<p>\r\n	These are the attributes of a listing:<br />\r\n	Title:<em> {your_site_title}</em><br />\r\n	URL: <em>{your_site_url}</em><br />\r\n	Description: <em>{your_site_desc}</em><br />\r\n	Email:<em> {your_site_email}</em></p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 82),
('email_templates', 'admin_notif_body_plaintext', 'Dear {admin_name},\r\n\r\nListing was submitted to {own_site} Directory. Please check it.\r\n\r\nThese are the attributes of a listing:\r\nTitle: {your_site_title}\r\nURL: {your_site_url}\r\nDescription: {your_site_desc}\r\nEmail: {your_site_email}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 82.1),
('email_templates', '', 'Submission Category Notification Email for Admin', '', 'divider', '', '', '0', 82.21),
('email_templates', 'suggest_category_subject', 'Category was submitted to {own_site}', '', 'text', 'Email subject', '', '0', 82.22),
('email_templates', 'suggest_category_body_html', '<h3>\r\n	Dear {admin_name},</h3>\r\n<p>\r\n	Category was submitted to <em><a href="{own_dir_url}">{own_site}</a></em>. Please check it.</p>\r\n<p>\r\n	These are the attributes of a category:<br />\r\n	Title:<em> {cat_title}</em><br />\r\n	Category path: <em>{cat_path}</em><br />\r\n	</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 82.23),
('email_templates', 'suggest_category_body_plaintext', 'Dear {admin_name},\r\n\r\nCategory was submitted to {own_site} Directory. Please check it.\r\n\r\nThese are the attributes of a category:\r\nTitle: {cat_title}\r\nCategory path: {cat_path}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 82.24),
('email_templates', '', 'Account Removed', '', 'divider', '', '', '0', 85.14),
('email_templates', 'account_deleted', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 85.15),
('email_templates', 'account_deleted_subject', 'Account deleted in {own_site}', '', 'text', 'Email subject', '', '0', 85.2),
('email_templates', 'account_deleted_body_html', '<h3>\r\n	Dear {username},</h3>\r\n<p>\r\n	Your account was removed from</p>\r\n<p>\r\n	<em><a href="{own_url}">{own_site}</a></em></p>\r\n<p>\r\n	Let us know if you have any questions.</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 85.3),
('email_templates', 'account_deleted_body_plaintext', 'Dear {username},\r\n\r\nYour account was removed from {own_site}. \r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 85.4),
('email_templates', '', 'Password Change Request', '', 'divider', '', '', '0', 86.5),
('email_templates', 'password_change_subject', 'Password change request at {own_site}', '', 'text', 'Email subject', '', '0', 87),
('email_templates', 'password_change_body_html', '<h3>\r\n	Dear {username},</h3>\r\n<p>\r\n	You requested a password change in <em><a href="{own_dir_url}">{own_site}</a></em>. Now you should use the following credentials to log in as account:</p>\r\n<p>\r\n	username:<strong> {username}</strong><br />\r\n	password: <strong>{password}</strong></p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 88),
('email_templates', 'password_change_body_plaintext', 'Dear {username},\r\n\r\nYou requested a password change in {own_site}. Now you should use the following credentials to log in as account:\r\n\r\nusername: {username}\r\npassword: {password}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 88.1),
('email_templates', '', 'Account Approved', '', 'divider', '', '', '0', 88.2),
('email_templates', 'account_approved', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 88.21),
('email_templates', 'account_approved_subject', 'Account was approved at {own_site}', '', 'text', 'Email subject', '', '0', 88.3),
('email_templates', 'account_approved_body_html', '<h3>\r\n	Dear {username},</h3>\r\n<p>\r\n	Your account was approved in <em><a href="{own_dir_url}">{own_site}</a></em>. Now you can log in to the directory.</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 88.4),
('email_templates', 'account_approved_body_plaintext', 'Dear {username},\r\n\r\nYour account was approved in {own_site}. Now you can log in to the directory.\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 88.5),
('email_templates', '', 'Account Dispproved', '', 'divider', '', '', '0', 88.6),
('email_templates', 'account_disapproved', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 88.65),
('email_templates', 'account_disapproved_subject', 'Account was disapproved at {own_site}', '', 'text', 'Email subject', '', '0', 88.7),
('email_templates', 'account_disapproved_body_html', '<h3>\r\n	Dear {username},</h3>\r\n<p>\r\n	Your account was disapproved in <em><a href="{own_dir_url}">{own_site}</a></em>.</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 88.8),
('email_templates', 'account_disapproved_body_plaintext', 'Dear {username},\r\n\r\nYour account was disapproved in {own_site}.\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 88.9),
('email_templates', '', 'Report broken link', '', 'divider', '', '', '0', 95.1),
('email_templates', 'broken_listing_report_subject', 'Broken Listing Reported at {own_site}', '', 'text', 'Subject: ', '', '0', 95.2),
('email_templates', 'broken_listing_report_body_html', '<h3>\r\n	Dear {admin_name},</h3>\r\n<p>\r\n	The following listing is reported as being broken:</p>\r\n<p>\r\n	Listing ID: {id}<br />\r\n	Listing URL: {url}<br />\r\n	Listing Title: {title}</p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you, <br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 95.3),
('email_templates', 'broken_listing_report_body_plaintext', 'Dear {admin_name},\r\n\r\nThe following listing is reported as being broken:\r\n\r\nListing ID: {id}\r\nListing URL: {url}\r\nListing Title: {title}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 95.31),
('email_templates', '', 'Account Confirm Email', '', 'divider', '', '', '0', 70),
('email_templates', 'account_confirm_email', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 70.1),
('email_templates', 'account_confirm_email_subject', 'Confirm email in {own_site}', '', 'text', 'Subject: ', '', '0', 70.2),
('email_templates', 'account_confirm_email_body_plaintext', 'Dear {username},\r\n\r\nWe have received new password request for your account ({username}) in {own_site}.\r\n\r\nIf this request was initiated by you, please click on following link to confirm your email:\r\n{own_site}confirm.php?action=restore_password&account={account_id}&r={sec_key}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 70.3),
('email_templates', 'account_confirm_email_body_html', '<h3>\r\n	Dear {username},</h3>\r\n<p>\r\n	We have received new password request for your account ({username}) in <em><a href="{own_dir_url}">{own_site}</a></em>.<br />\r\n	<br />\r\n	If this request was initiated by you, please click on following link to confirm your email:<br />\r\n	<em><a href="{own_dir_url}confirm.php?action=restore_password&amp;account={account_id}&amp;r={sec_key}">{own_dir_url}confirm.php?action=restore_password&amp;account={account_id}&amp;r={sec_key}</a></em></p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you,<br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 70.4),
('email_templates', '', 'Account Confirm Change Email', '', 'divider', '', '', '0', 70.5),
('email_templates', 'account_change_email', '1', '''1'',''0''', 'radio', 'Email sending', '', '0', 70.6),
('email_templates', 'account_change_email_subject', 'Confirm change email in {own_site}', '', 'text', 'Subject: ', '', '0', 70.7),
('email_templates', 'account_change_email_body_plaintext', 'Dear {username},\r\n\r\nWe have received change email request for your account ({username}) in {own_site}.\r\n\r\nIf this request was initiated by you, please click on following link to confirm your email:\r\n{own_site}confirm.php?action=change_email&account={account_id}&r={sec_key}\r\n\r\n______________________________\r\nThank you,\r\n{own_site} Administration Team\r\n{own_url}\r\n{own_email}', '', 'textarea', 'Email Body', '', '0', 70.8),
('email_templates', 'account_change_email_body_html', '<h3>\r\n	Dear {username},</h3>\r\n<p>\r\n	We have received change email request for your account ({username}) in <em><a href="{own_dir_url}">{own_site}</a></em>.<br />\r\n	<br />\r\n	If this request was initiated by you, please click on following link to confirm your email:<br />\r\n	<em><a href="{own_dir_url}confirm.php?action=change_email&amp;account={account_id}&amp;r={sec_key}">{own_dir_url}confirm.php?action=change_email&amp;account={account_id}&amp;r={sec_key}</a></em></p>\r\n<p>\r\n	______________________________<br />\r\n	Thank you,<br />\r\n	{own_site} Administration Team<br />\r\n	{own_url}<br />\r\n	{own_email}</p>\r\n', '', 'textarea', 'HTML Body', '', '1', 70.9),
('comments', 'div_comments', 'Comments Configuration', '', 'divider', 'Comments Configuration', 'comments', '0', 122.1),
('comments', 'allow_listing_comments_submission', '1', '1,0', 'radio', 'Allow listing comments submission', 'comments', '0', 123.1),
('comments', 'listing_comments_accounts', '1', '1,0', 'radio', 'Allows to comment for guests', 'comments', '0', 124.1),
('comments', 'html_comments', '0', '1,0', 'radio', 'Allows WYSIWYG', 'comments', '0', 125.1),
('comments', 'comments_approval', '0', '1,0', 'radio', 'Comments auto approval', 'comments', '0', 126.1),
('comments', 'comment_min_chars', '10', '', 'text', 'Min number of chars for listing comment', 'comments', '0', 127.1),
('comments', 'comment_max_chars', '300', '', 'text', 'Max number of chars for listing comment', 'comments', '0', 128.1),
('comments', 'num_latest_comments', '5', '', 'text', 'Number of latest comments in block', 'comments', '0', 129.1),
('comments', 'div_rating', 'Rating Configuration', '', 'divider', 'Rating Configuration', 'comments', '0', 130.1),
('comments', 'listing_rating', '1', '1,0', 'radio', 'Listings Rating', 'comments', '0', 131.1),
('comments', 'listing_rating_max', '10', '', 'text', 'Maximum listings rating', 'comments', '0', 132.1),
('comments', 'listing_rating_block_max', '10', '', 'text', 'Maximum listings in block rating', 'comments', '0', 133.1),
('comments', 'rate_period', '1', '', 'text', 'Rate period for IP (in days)', 'comments', '0', 134.1);

